# Generated by Django 5.1.6 on 2025-06-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0011_alter_category_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='video_url',
        ),
    ]
